on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: DockerHub Build And Push
      uses: Abhishek-070/Dockerhub-Build-Push@v1.0
      with:
          registry_url: 'docker.io'
          repository_name: 'hvpaiva/java-11-certificated'
          user_name: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_version: '0.0.2'
          docker_file: '.'
    - name: Get pre step result output image_pull_url
      run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"

